### ISSUE TITLE
getting error while generating

### ISSUE THREAD

**Issue by nekhoroshikh** [CONIGUERO/gitlab-license#3]
after execution of gitlabgen.rb and answer 3 questions i have this output:

Traceback (most recent call last):
        2: from gitlabgen.rb:60:in `<main>'
        1: from /opt/rh/rh-ruby27/root/usr/local/share/gems/gems/gitlab-license-2.3.0/lib/gitlab/license.rb:243:in `export'
/opt/rh/rh-ruby27/root/usr/local/share/gems/gems/gitlab-license-2.3.0/lib/gitlab/license.rb:123:in `validate!': License is invalid (Gitlab::License::ValidationError)

gitlab 15.11.6-ee

**Comment by alexeyvs** [comment]
set dates in gitlabgen.rb which are now required 
license.starts_at         = Date.today
license.expires_at        = Date.today + 3650
